project:
  type: website
  render:
    - "*.qmd"
    - "!todo/*"
    - "!archive_2122/*"
    - "!archive_2223/*"
  output-dir: ../docs/2324/labs/

website:
  title: "DAPR1"
  page-footer: 
    left: "Â© Copyright 2019-2023 [The University of Edinburgh](https://www.ed.ac.uk/). Site licensed under the [GNU AGPLv3](https://www.gnu.org/licenses/agpl-3.0.en.html) license."
  page-navigation: true
  reader-mode: true
  back-to-top-navigation: true
  search: true
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Lab Materials"
        menu: 
          - text: "<b>Block 1: Exploratory data analysis</b>"
          - text: "S1-W1: Research design & data"
            file: 1_01_design_and_data.qmd
          - text: "S1-W2: Categorical data"
            file: 1_02_categorical_data.qmd
          # - text: "S1-W3: Numeric data"
          #   file: 1_03_numeric_data.qmd
          # - text: "S1-W4: Relationships"
          #   file: 1_04_relationships.qmd
          # - text: "S1-W5: Formative Report A"
          #   file: 1_05_formative_report_a.qmd
          # - text: "---"
          # - text: "<b>Block 2: Probability</b>"
          # - text: "S1-W7: Probability Theory"
          #   file: 1_07_prob_theory.qmd
          # - text: "S1-W8: Probability Rules"
          #   file: 1_08_prob_rules.qmd
          # - text: "S1-W9: Discrete Random Variables"
          #   file: 1_09_discrete_dist.qmd
          # - text: "S1-W10: Continuous Random Variables"
          #   file: 1_10_cont_dist.qmd
          # - text: "S1-W11: Formative Report B"
          #   file: 1_11_sampling.qmd
          # - text: "---"
          # - text: "<b>Block 3: Inference</b>"
          # - text: "S2-W1: Confidence intervals"
          #   file: 2_01_confint.qmd
          # - text: "S2-W2: HT (p-values)"
          #   file: 2_02_ht_pvalues.qmd
          # - text: "S2-W3: HT (critical values)"
          #   file: 2_03_ht_critvalues.qmd
          # - text: "S2-W4: Connecting HT and CIs"
          #   file: 2_04_htci.qmd
          # - text: "S2-W5: Formative Report C"
          #   file: 2_05_hterrorspower.qmd
          # - text: "---"
          # - text: "<b>Block 4: Assessed report</b>"
          # - text: "Assessment information on LEARN"
          # - text: "[S2-FLW: Formative Feedback Week]"
          # - text: "---"
          # - text: "<b>Block 4: Common hypothesis tests</b>"
          # - text: "S2-W6---S2-W10: Assessed Report"
          # - text: "S2-FLW: Formative feedback C"
          # - text: "S2-W6: One sample t-test"
          # - text: "S2-W7: Independent samples t-test"
          # - text: "S2-W8: Paired samples t-test"
          # - text: "S2-W9: Chi-square tests"
          # - text: "S2-W10: Covariance and correlation"
    right:
      - text: "Readings"
        menu: 
          - text: "<b>Block 1: Exploratory data analysis</b>"
          - text: "S1-W1: Getting started with R and RStudio"
            file: rd1_01.qmd
          - text: "S1-W2: Categorical data"
            file: rd1_02.qmd
          - text: "S1-W3: Numeric data"
            file: rd1_03.qmd
          - text: "S1-W4: Relationships"
            file: rd1_04.qmd
          - text: "S1-W5: Functions"
            file: rd1_05.qmd
          - text: "---"
          - text: "<b>Block 2: Probability</b>"
          - text: "S1-W7: Probability 1"
            file: rd1_07.qmd
          - text: "S1-W8: Probability 2"
            file: rd1_08.qmd
          - text: "S1-W9: Discrete random variables"
            file: rd1_09.qmd
          - text: "S1-W10: Continuous random variables"
            file: rd1_10.qmd
          - text: "S1-W11: Sampling"
            file: rd1_11.qmd
          - text: "---"
          - text: "<b>Block 3: Inference</b>"
          - text: "S2-W1: Confidence intervals"
            file: rd2_01.qmd
          - text: "S2-W2: HT (p-values)"
            file: rd2_02.qmd
          - text: "S2-W3: HT (critical values)"
            file: rd2_03.qmd
          - text: "S2-W4: Connecting HT and CIs"
            file: rd2_04.qmd
          - text: "S2-W5: Errors, Power, Effect size, Assumptions"
            file: rd2_05.qmd
      - text: "About"
        file: about.qmd
        
bibliography: biblio.bib

format:
  html:
    highlight-style: a11y
    theme:
      light: flatly
      dark: darkly
    css: assets/styles.css
    include-in-header: assets/toggling.html
    toc: true
    code-link: true
    sidebar: true
    number-sections: true
